linters-settings:
  gocritic:
    disabled-checks:
      - singleCaseSwitch
      - commentFormatting
    enabled-tags:
      - performance
      - diagnostic
      - style
      - opinionated

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - exhaustivestruct
    - forcetypeassert
    - nonamedreturns
    - testpackage
    - tagliatelle
    - exhaustruct
    - varnamelen
    - forbidigo
    - gofumpt
    - gomnd
    - gci
  fast: false

output:
  format: 'colored-line-number'
  print-issued-lines: true
  print-linter-name: true

issues:
  exclude-rules:
    - path: ._test\.go
      linters:
        - goerr113
