linters-settings:
  gocritic:
    disabled-checks:
      - singleCaseSwitch
      - commentFormatting
    enabled-tags:
      - performance
      - diagnostic
      - style
      - opinionated

linters:
  enable-all: true
  disable:
    # useless
    - exhaustivestruct
    - gochecknoglobals
    - gomnd
    - gofumpt
    - gci
    - testpackage
    - cyclop
    - goerr113
    - funlen
    - tagliatelle
    # deprecated
    - interfacer
    - maligned
    - scopelint
    - golint
  fast: false

output:
  format: 'colored-line-number'
  print-issued-lines: true
  print-linter-name: true

