name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: test-cover
        run: make test-cover
      - name: install-reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > cc-test-reporter
          chmod u+x cc-test-reporter
      - name: before-build
        run: ./cc-test-reporter before-build
      - name: format
        run: ./cc-test-reporter format-coverage test.cover --input-type gocov test.cover --prefix github.com/s0rg/phpunisher
      - name: after-build
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: ./cc-test-reporter upload-coverage

