name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: make lint
      - run: make test

